name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Test, Dependabot ]
    types: 
      - completed

jobs:
  release:
    if: |
      github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' &&
        (github.event.workflow_run.name == 'Test' && github.event.workflow_run.head_branch == 'main' ||
         github.event.workflow_run.name == 'Dependabot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Delete Old Release
        uses: actions/github-script@v7
        with:
          script: |
            let release
            try {
              release = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              })
            } catch(e) {
              console.error(e)
              return
            }

            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })

            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/'+release.data.tag_name
            })

      - name: Build
        id: build
        run: |
          make build
          mv requirements-linux-amd64 requirements
          tar cvzf release-linux-amd64.tar.gz dist requirements
          mv -f requirements-darwin-arm64 requirements
          tar cvzf release-darwin-arm64.tar.gz dist requirements
          mv -f requirements-darwin-amd64 requirements
          tar cvzf release-darwin-amd64.tar.gz dist requirements
          mv requirements-windows-amd64.exe requirements.exe
          zip -9vr release-windows.zip dist requirements.exe
          echo "date=$(TZ=PRC date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.date }}
          name: ${{ steps.build.outputs.date }}
          body: ${{ steps.build.outputs.date }}
          files: release*
